MODEL:
  TYPE: 'VM_ASR'
  NAME: 'VMUNet'
  VSSM:
    DEPTHS: [2, 2, 2, 2]
    DIMS: 32
    SSM_D_STATE: 16
    SSM_DT_RANK: "auto"
    SSM_RATIO: 1.0
    SSM_CONV: 3
    SSM_CONV_BIAS: false
    SSM_FORWARDTYPE: "v04_ondwconv3"
    MLP_RATIO: 4.0
    DROP_PATH_RATE: 0.2
    DOWNSAMPLE: "v3"
    UPSAMPLE: "v2"
    PATCHEMBED: "v2"
    NORM_LAYER: "ln"
    OUTPUT: "v1"
    CONCAT_SKIP: True
    SKIP_CONNECT_PATCH: True
    DROP_LAST_ENCODER: True

TRAIN:
  EARLY_STOPPING: 10
  LOSSES:
    GEN: ["multi_resolution_stft", "l2"]
    STFT_LOSS:
      SC_FACTOR: 1.0
      MAG_FACTOR: 1.0
      PHASE_FACTOR: 0.0

  LOW_FREQ_REPLACEMENT: False
  CLIP_GRAD:
    ENABLE: True
    MAX_NORM: 1e-2
  GRADIENT_PENALTY:
    ENABLE: False
  ADVERSARIAL:
    ENABLE: True
    DISCRIMINATORS: ["mpd"]
    GAN_LOSS_TYPE: "lsgan"
  BASE_LR_G: 1e-4
  BASE_LR_D: 1e-5

DATA:
  BATCH_SIZE: 6
  TARGET_SR: 48000
  SEGMENT: 2.555
  USE_QUANTITY: 1.0
  VALID_SPLIT: 0.1
  WEIGHTED_SR:
    ENABLE: True
  LPF:
    MULTIFILTER: True
  NUM_WORKERS: 10

DEBUG: False

WANDB:
  ENABLE: True
  TAGS: ["48k", "Data_1.0", "MPD", "LS-GAN", "SINGLE"]