MODEL:
  TYPE: 'VM_ASR'
  NAME: 'DualStreamInteractiveMambaUNet'
  VSSM:
    DIMS: 16

TRAIN:
  EARLY_STOPPING: 10
  LOSSES:
    STFT_LOSS:

  LOW_FREQ_REPLACEMENT: True
  ADVERSARIAL:
    ENABLE: True
    DISCRIMINATORS: ["mpd"]
    GAN_LOSS_TYPE: "wgan-gp"

DATA:
  BATCH_SIZE: 8
  TARGET_SR: 16000
  USE_QUANTITY: 0.1
  VALID_SPLIT: 0.1
  WEIGHTED_SR:
    ENABLE: False
  LPF:
    MULTIFILTER: True

DEBUG: False

WANDB:
  ENABLE: True
  TAGS: ["16k", "Data_0.1", "MPD", "WGAN-GP"]