MODEL:
  TYPE: 'VM_ASR'
  NAME: 'DualStreamInteractiveMambaUNet'
  VSSM:
    DIMS: 16

TRAIN:
  EARLY_STOPPING: 0
  ACCUMULATION_STEPS: 1
  LOW_FREQ_REPLACEMENT: True
  ADVERSARIAL:
    ENABLE: True
    DISCRIMINATORS: ["mpd"]

DATA:
  BATCH_SIZE: 6
  TARGET_SR: 48000
  USE_QUANTITY: 0.1
  VALID_SPLIT: 0.1
  RANDOM_RESAMPLE: [8000, 48000]
  LPF:
    MULTIFILTER: True

DEBUG: False

WANDB:
  ENABLE: False