MODEL:
  TYPE: 'VM_ASR'
  NAME: 'DualStreamInteractiveMambaUNet'
  VSSM:
    IN_CHANS: 1
    DEPTHS: [2, 2, 2, 2]
    DIMS: 16
    SSM_D_STATE: 1
    SSM_FORWARDTYPE: "v5"
    DROP_PATH_RATE: 0.1
    PATCHEMBED:  "v2"
    DOWNSAMPLE:  "v1"
    UPSAMPLE:  "v1"
    OUTPUT:  "v3"
    CONCAT_SKIP: True

TRAIN:
  EARLY_STOPPING: 0
  ACCUMULATION_STEPS: 1
  LOW_FREQ_REPLACEMENT: True
  ADVERSARIAL:
    ENABLE: True
    DISCRIMINATORS: ["mpd"]
    FEATURE_LOSS_LAMBDA: 100
    ONLY_FEATURE_LOSS: False
    ONLY_ADVERSARIAL_LOSS: False

DATA:
  BATCH_SIZE: 8
  TARGET_SR: 16000
  USE_QUANTITY: 0.001
  VALID_SPLIT: 0.2
  RANDOM_RESAMPLE: [8000]
  LPF:
    MULTIFILTER: True

DEBUG: False

WANDB:
  ENABLE: False