MODEL:
  TYPE: 'VM_ASR'
  NAME: 'DualStreamInteractiveMambaUNet'
  VSSM:
    DIMS: 16

TRAIN:
  EARLY_STOPPING: 0
  ACCUMULATION_STEPS: 1
  LOW_FREQ_REPLACEMENT: True
  ADVERSARIAL:
    ENABLE: True
    DISCRIMINATORS: ["mpd"]

DATA:
  BATCH_SIZE: 8
  TARGET_SR: 16000
  USE_QUANTITY: 0.1
  VALID_SPLIT: 0.1
  WEIGHTED_SR:
    ENABLE: True
  LPF:
    MULTIFILTER: True

DEBUG: False

WANDB:
  ENABLE: True