MODEL:
  TYPE: 'VM_ASR'
  NAME: 'MambaUNet'
  VSSM:
    DIMS: 16
    PATCHEMBED: "v2"
    DOWNSAMPLE: "v3"
    UPSAMPLE: "v2"
    OUTPUT: "v3"
    CONCAT_SKIP: True
    SKIP_CONNECT_PATCH: False
    DROP_LAST_ENCODER: False

TRAIN:
  EARLY_STOPPING: 10
  LOSSES:
    STFT_LOSS:
      SC_FACTOR: 1.0
      MAG_FACTOR: 1.0
      PHASE_FACTOR: 0.2

  LOW_FREQ_REPLACEMENT: True
  CLIP_GRAD:
    ENABLE: False
  ADVERSARIAL:
    ENABLE: False
    DISCRIMINATORS: ["mpd"]
    GAN_LOSS_TYPE: "lsgan"

DATA:
  BATCH_SIZE: 60
  NUM_WORKERS: 2
  TARGET_SR: 16000
  USE_QUANTITY: 0.1
  VALID_SPLIT: 0.1
  WEIGHTED_SR:
    ENABLE: True
  LPF:
    MULTIFILTER: True

DEBUG: False

WANDB:
  ENABLE: True
  TAGS: ["16k", "Data_0.1", "Single-Stream", "MPD", "LS-GAN"]