MODEL:
  TYPE: 'VM_ASR'
  NAME: 'DualStreamVMUNet'
  VSSM:
    DIMS: 16

TRAIN:
  EARLY_STOPPING: 10
  LOSSES:
    STFT_LOSS:

  LOW_FREQ_REPLACEMENT: True
  ADVERSARIAL:
    ENABLE: True
    DISCRIMINATORS: ["mpd"]

DATA:
  BATCH_SIZE: 4
  TARGET_SR: 48000
  USE_QUANTITY: 0.1
  VALID_SPLIT: 0.1
  WEIGHTED_SR:
    ENABLE: False
  LPF:
    MULTIFILTER: True

DEBUG: False

WANDB:
  ENABLE: True
  TAGS: ["48k", "Data_0.1", "MPD"]