MODEL:
  TYPE: 'VM_ASR'
  NAME: 'DualStreamInteractiveMambaUNet'
  VSSM:
    IN_CHANS: 1
    DEPTHS: [2, 2, 2, 2]
    DIMS: [64, 128, 256, 512]
    SSM_D_STATE: 1
    SSM_FORWARDTYPE: "v5"
    DROP_PATH_RATE: 0.1
    PATCHEMBED:  "v2"
    DOWNSAMPLE:  "v1"
    UPSAMPLE:  "v1"
    OUTPUT:  "v3"
    CONCAT_SKIP: True

TRAIN:
  ADVERSARIAL:
    ENABLE: False

DATA:
  USE_QUANTITY: 0.1
  RANDOM_RESAMPLE: [8000]

WANDB:
  ENABLE: False